$ShowError = $false
$ShowGit = $false
$ShowUser = $false
$ShowAzure = $false
$ShowAzureCli = $false
$ShowPath = $false
$ShowCountDown = $true
$CountDownMessage = "Global Azure"
$CountDownEndDate = Get-Date -Year 2022 -Month 05 -Day 07 -Hour 09 -Minute 30