name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths: 
      - datagrillen1/dockerfile
      - datagrillen2/dockerfile
    
  pull_request:
    branches: [ main ]
    paths:
      - datagrillen1/dockerfile
      - datagrillen2/dockerfile
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - 
        name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1.36.0
        env:
          DEFAULT_BUMP: minor
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push First Container
        uses: docker/build-push-action@v2
        with:
          push: true
          context: datagrillen1/
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/datagrillen1:${{ steps.bump.outputs.new_tag }},${{ secrets.DOCKERHUB_USERNAME }}/datagrillen1:latest
      -
        name: Build and push Sql Instance 2
        uses: docker/build-push-action@v2
        with:
          push: true
          context: datagrillen2/
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/datagrillen2:${{ steps.bump.outputs.new_tag }},${{ secrets.DOCKERHUB_USERNAME }}/datagrillen2:latest
      -
        name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "datagrillen1:.*"
          replace: "datagrillen1:${{ steps.bump.outputs.new_tag }}"
          include: ".devcontainer/docker-compose.yml" 
      -
        name: Find and Replace datagrillen2
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "datagrillen2:.*"
          replace: "datagrillen2:${{ steps.bump.outputs.new_tag }}"
          include: ".devcontainer/docker-compose.yml" 
      -
        name: Add & Commit
        uses: EndBug/add-and-commit@v8.0.2
        with:
          author_name: Beardy McBeardFace
          author_email: mrrobsewell@outlook.com
          message: 'The Beard says we have another one - This is an automated message'



