SELECT TOP (100) [Sql Hash]
      ,[Interval Duration (min)]
      ,[Interval End Time]
      ,[Elapsed Time (min)]
      ,[Application]
      ,[Database]
      ,[Host]
      ,[Login]
      ,[Avg Cpu (µs)]
      ,[Min Cpu (µs)]
      ,[Max Cpu (µs)]
      ,[Sum Cpu (µs)]
      ,[Avg Reads]
      ,[Min Reads]
      ,[Max Reads]
      ,[Sum Reads]
      ,[Avg Writes]
      ,[Min Writes]
      ,[Max Writes]
      ,[Sum Writes]
      ,[Avg Duration (µs)]
      ,[Min Duration (µs)]
      ,[Max Duration (µs)]
      ,[Sum Duration (µs)]
      ,[Execution Count]
  FROM [WorkLoadTools].[baseline].[PowerBI_WorkloadData]
  SELECT TOP (100) [Sql Hash]
      ,[Interval Duration (min)]
      ,[Interval End Time]
      ,[Elapsed Time (min)]
      ,[Application]
      ,[Database]
      ,[Host]
      ,[Login]
      ,[Avg Cpu (µs)]
      ,[Min Cpu (µs)]
      ,[Max Cpu (µs)]
      ,[Sum Cpu (µs)]
      ,[Avg Reads]
      ,[Min Reads]
      ,[Max Reads]
      ,[Sum Reads]
      ,[Avg Writes]
      ,[Min Writes]
      ,[Max Writes]
      ,[Sum Writes]
      ,[Avg Duration (µs)]
      ,[Min Duration (µs)]
      ,[Max Duration (µs)]
      ,[Sum Duration (µs)]
      ,[Execution Count]
  FROM [WorkLoadTools].[replay].[PowerBI_WorkloadData]